version: '2.1'
services:
  jhipster-registry:
    image: jhipster/jhipster-registry:v6.2.0
    volumes:
      - ./gateway/src/main/docker/central-server-config:/central-config
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,swagger
      - SPRING_SECURITY_USER_PASSWORD=admin
      - JHIPSTER_REGISTRY_PASSWORD=admin
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/localhost-config/
    ports:
      - 8761:8761

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    depends_on:
      - jhipster-registry
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:5.5.0
    depends_on:
      - jhipster-registry
      - zookeeper
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  bookcatalog-mongodb:
    network_mode: bridge
    image: mongo:4.2.7
    depends_on:
      - jhipster-registry
    ports:
      - 27017:27017
    # volumes:
    #     - ~/volumes/jhipster/bookCatalog/mongodb/:/data/db/

  gateway:
    network_mode: bridge
    build:
      context: ./gateway
      dockerfile: Dockerfile
    depends_on:
      - jhipster-registry
    ports:
      - 8080:8080
    # links:
    #   - jhipster-registry
    #   - kafka
    #   - bookcatalog-mongodb
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    # volumes:
    #   - .:/app
    # command: ["./mvnw"]

  book:
    network_mode: bridge
    build: ./book
    depends_on:
      - jhipster-registry
    ports:
      - 8081:8081
    # links:
    #   - jhipster-registry
    # volumes:
    #   - .:/app
    # command: ["./mvnw"]

  bookcatalog:
    network_mode: bridge
    build: ./bookCatalog
    depends_on:
      - jhipster-registry
    ports:
      - 8082:8082
    # links:
    #   - jhipster-registry
    # volumes:
    #   - .:/app
    # command: ["./mvnw"]

  rental:
    network_mode: bridge
    build: ./rental
    depends_on:
      - jhipster-registry
    ports:
      - 8083:8083
    # links:
    #   - jhipster-registry
    # volumes:
    #   - .:/app

