networks:
  jhipster-registry_net1:
    external: true
version: '2'
services:
  gateway:
    build: .
    ports:
      - 8082:8082
    volumes:
      - .:/app
    command: ["./mvnw"]
    networks:
      - jhipster-registry_net1